# SECURITY WARNING: keep the secret key used in production secret!
# Ключ шифрования 
# Пожалуйста, измените его на случайную строку в производственной среде, не допускайте утечки
# Dы можете использовать команду для генерации
# $ cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49;echo
SECRET_KEY:

# SECURITY WARNING: keep the bootstrap token used in production secret!
# Pre-shared Token coco и guacamole используются для регистрации сервисных аккаунтов вместо использования оригинального механизма принятия регистрации.
BOOTSTRAP_TOKEN:

# Development env open this, when error occur display the full process track, Production disable it
# DEBUG: true

# DEBUG, INFO, WARNING, ERROR, CRITICAL can set. See https://docs.djangoproject.com/en/1.10/topics/logging/
# LOG_LEVEL: DEBUG
# LOG_DIR:

# Session expiration setting, Default 1 hour, Also set expired on on browser close
# SESSION_COOKIE_AGE: 3600
# SESSION_EXPIRE_AT_BROWSER_CLOSE: false

# Database setting, Support sqlite3, mysql, postgres ....
# See https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# SQLite setting:
# DB_ENGINE: sqlite3
# DB_NAME:
# MySQL or postgres setting like:
DB_ENGINE: mysql
DB_HOST: 127.0.0.1
DB_PORT: 3306
DB_USER: jumpserver
DB_PASSWORD:
DB_NAME: jumpserver

# When Django start it will bind this host and port
# ./manage.py runserver 127.0.0.1:8080
HTTP_BIND_HOST: 0.0.0.0
HTTP_LISTEN_PORT: 8080
WS_LISTEN_PORT: 8070

# Use Redis as broker for celery and web socket
REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
# REDIS_PASSWORD:
# REDIS_DB_CELERY: 3
# REDIS_DB_CACHE: 4

# LDAP/AD settings
# AUTH_LDAP_SEARCH_PAGED_SIZE: 1000
# AUTH_LDAP_SYNC_IS_PERIODIC: True

# AUTH_LDAP_SYNC_INTERVAL: 12

# AUTH_LDAP_SYNC_CRONTAB: * 6 * * *
# AUTH_LDAP_USER_LOGIN_ONLY_IN_USERS: False

# In order to perform this operation a successful bind must be completed on the connection
# AUTH_LDAP_OPTIONS_OPT_REFERRALS: -1

# OTP settings

# OTP_VALID_WINDOW: 0
# OTP_ISSUER_NAME: Jumpserver

# PERIOD_TASK_ENABLED: True

# WINDOWS_SKIP_ALL_MANUAL_PASSWORD: False

# SECURITY_WATERMARK_ENABLED: False

# SESSION_EXPIRE_AT_BROWSER_CLOSE_FORCE: False

# SESSION_SAVE_EVERY_REQUEST: True

# ONLY_ALLOW_AUTH_FROM_SOURCE: False

# ONLY_ALLOW_EXIST_USER_AUTH: False
