# Generated by Django 2.1.1 on 2018-10-16 02:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0022_auto_20181012_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('provider', models.CharField(choices=[('aliyun', '阿里云'), ('aws_china', 'AWS (中国)'), ('aws_international', 'AWS (国际)')], default='aliyun', max_length=128, verbose_name='云服务商')),
                ('_access_key_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Access key id')),
                ('_access_key_secret', models.CharField(blank=True, max_length=128, null=True, verbose_name='Access key secret')),
                ('validity', models.BooleanField(choices=[(True, '有效'), (False, '无效')], default=False, max_length=2, verbose_name='账户状态')),
                ('comment', models.TextField(blank=True, default='', max_length=128, verbose_name='备注')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建者')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '账户',
            },
        ),
        migrations.CreateModel(
            name='SyncInstanceDetail',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(blank=True, max_length=128, verbose_name='实例')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='地域')),
                ('status', models.SmallIntegerField(choices=[(0, '失败'), (1, '成功'), (2, '存在')], default=1, verbose_name='状态')),
                ('date_sync', models.DateTimeField(auto_now=True, null=True, verbose_name='同步日期')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset', verbose_name='资产')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncInstanceTask',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('regions', models.CharField(blank=True, max_length=1024, verbose_name='地域')),
                ('instances', models.CharField(blank=True, max_length=1024, null=True, verbose_name='实例')),
                ('comment', models.TextField(blank=True, default='', max_length=2048, verbose_name='备注')),
                ('date_last_sync', models.DateTimeField(auto_now=True, null=True, verbose_name='最后同步日期')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建者')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.Account', verbose_name='账户')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.AdminUser', verbose_name='管理用户')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '同步实例任务',
            },
        ),
        migrations.CreateModel(
            name='SyncInstanceTaskHistory',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=2048, verbose_name='结果')),
                ('status', models.SmallIntegerField(choices=[(0, '失败'), (1, '成功'), (2, 'Partial succeed')], default=1, verbose_name='状态')),
                ('reason', models.CharField(blank=True, default='-', max_length=128, verbose_name='原因')),
                ('date_sync', models.DateTimeField(auto_now_add=True, null=True, verbose_name='同步日期')),
                ('sync_instance_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.SyncInstanceTask', verbose_name='同步实例任务')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='syncinstancedetail',
            name='sync_instance_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.SyncInstanceTask', verbose_name='同步任务'),
        ),
        migrations.AddField(
            model_name='syncinstancedetail',
            name='sync_instance_task_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.SyncInstanceTaskHistory', verbose_name='同步实例任务历史'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='syncinstancetask',
            unique_together={('org_id', 'name')},
        ),
    ]
