# Generated by Django 2.1.1 on 2018-10-16 02:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0022_auto_20181012_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='имя')),
                ('provider', models.CharField(choices=[('aliyun', 'Ali Cloud'), ('aws_china', 'AWS (Китай)'), ('aws_international', 'AWS (Международный)')], default='aliyun', max_length=128, verbose_name='Облачный провайдер')),
                ('_access_key_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Access key id')),
                ('_access_key_secret', models.CharField(blank=True, max_length=128, null=True, verbose_name='Access key secret')),
                ('validity', models.BooleanField(choices=[(True, 'Валидный'), (False, 'Невалидный')], default=False, max_length=2, verbose_name='Статус аккаунта')),
                ('comment', models.TextField(blank=True, default='', max_length=128, verbose_name='Комментарий')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Кем создан')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Учётная запись',
            },
        ),
        migrations.CreateModel(
            name='SyncInstanceDetail',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(blank=True, max_length=128, verbose_name='Пример')),
                ('region', models.CharField(blank=True, max_length=128, verbose_name='Регион')),
                ('status', models.SmallIntegerField(choices=[(0, 'Провал'), (1, 'Успех'), (2, 'Существует')], default=1, verbose_name='Статус')),
                ('date_sync', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время синхронизации')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset', verbose_name='Ресурс')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncInstanceTask',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('regions', models.CharField(blank=True, max_length=1024, verbose_name='Регионы')),
                ('instances', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Экземпляры')),
                ('comment', models.TextField(blank=True, default='', max_length=2048, verbose_name='Комментарий')),
                ('date_last_sync', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последней синхронизации')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='Кем создано')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.Account', verbose_name='Учётная запись')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.AdminUser', verbose_name='Администратор')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Node', verbose_name='Нода')),
            ],
            options={
                'verbose_name': 'Задача синхронизации экземпляра',
            },
        ),
        migrations.CreateModel(
            name='SyncInstanceTaskHistory',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=2048, verbose_name='Результат')),
                ('status', models.SmallIntegerField(choices=[(0, 'Провал'), (1, 'Успех'), (2, 'Частичный успех')], default=1, verbose_name='Статус')),
                ('reason', models.CharField(blank=True, default='-', max_length=128, verbose_name='Причина')),
                ('date_sync', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время синхронизации')),
                ('sync_instance_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.SyncInstanceTask', verbose_name='Задача синхронизации экземпляра')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='syncinstancedetail',
            name='sync_instance_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.SyncInstanceTask', verbose_name='Синхронизировать задачу'),
        ),
        migrations.AddField(
            model_name='syncinstancedetail',
            name='sync_instance_task_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpack.SyncInstanceTaskHistory', verbose_name='Синхронизировать историю задач экземпляра'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('org_id', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='syncinstancetask',
            unique_together={('org_id', 'name')},
        ),
    ]
