# Generated by Django 2.1.1 on 2018-12-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('aliyun', '阿里云'), ('qcloud', '腾讯云'), ('aws_china', 'AWS (中国)'), ('aws_international', 'AWS (国际)')], default='aliyun', max_length=128, verbose_name='云服务商'),
        ),
        migrations.AlterField(
            model_name='syncinstancetaskhistory',
            name='result',
            field=models.TextField(blank=True, default='', verbose_name='结果'),
        ),
    ]
