# Generated by Django 2.1.1 on 2018-12-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('aliyun', 'Ali Cloud'), ('qcloud', 'Tencent Cloud'), ('aws_china', 'AWS (Китай)'), ('aws_international', 'AWS (Международный)')], default='aliyun', max_length=128, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='syncinstancetaskhistory',
            name='result',
            field=models.TextField(blank=True, default='', verbose_name='Результат'),
        ),
    ]
