# Generated by Django 2.1 on 2019-01-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0002_auto_20181204_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='validity',
            field=models.BooleanField(choices=[(True, '有效'), (False, '无效')], default=False, max_length=2, verbose_name='有效'),
        ),
    ]
