# Generated by Django 2.1.7 on 2019-02-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0004_interface_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Cloud account'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': '许可证'},
        ),
    ]
