# Generated by Django 2.1.7 on 2019-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0007_auto_20190402_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeauthplan',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='changeauthplan',
            unique_together={('org_id', 'name')},
        ),
    ]
