# Generated by Django 2.1.7 on 2019-09-18 08:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0041_gathereduser'),
        ('xpack', '0010_auto_20190729_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatherUserTask',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('is_periodic', models.BooleanField(default=False, verbose_name='Periodic')),
                ('interval', models.IntegerField(blank=True, default=24, null=True, validators=[django.core.validators.MaxValueValidator(8760), django.core.validators.MinValueValidator(1)], verbose_name='Cycle perform')),
                ('crontab', models.CharField(blank=True, max_length=128, null=True, verbose_name='Regularly perform')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=128, null=True, verbose_name='Created by')),
                ('nodes', models.ManyToManyField(blank=True, related_name='gather_user_task', to='assets.Node', verbose_name='Nodes')),
            ],
            options={'ordering': ['name'], 'verbose_name': 'Gather user task'},
        ),
        migrations.CreateModel(
            name='GatherUserTaskExecution',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Date start')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('success', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='xpack.GatherUserTask', verbose_name='Task')),
            ],
            options={'verbose_name': 'gather user task execution'},
        ),
        migrations.AlterUniqueTogether(
            name='gatherusertask',
            unique_together={('org_id', 'name')},
        ),
    ]
