# Generated by Django 2.2.10 on 2020-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0011_auto_20190918_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('aliyun', 'Alibaba Cloud'), ('qcloud', 'Tencent Cloud'), ('aws_china', 'AWS (China)'), ('aws_international', 'AWS (International)'), ('huaweicloud', 'Huawei Cloud')], default='aliyun', max_length=128, verbose_name='Provider'),
        ),
    ]
