# Generated by Django 2.2.10 on 2020-03-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0012_auto_20200210_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeauthplan',
            name='interval',
            field=models.IntegerField(blank=True, default=24, null=True, verbose_name='Cycle perform'),
        ),
        migrations.AlterField(
            model_name='changeauthplan',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gatherusertask',
            name='interval',
            field=models.IntegerField(blank=True, default=24, null=True, verbose_name='Cycle perform'),
        ),
        migrations.AlterField(
            model_name='gatherusertask',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='syncinstancetask',
            name='interval',
            field=models.IntegerField(blank=True, default=24, null=True, verbose_name='Cycle perform'),
        ),
    ]
