# Generated by Django 2.2.10 on 2020-03-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0013_auto_20200302_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncinstancetaskhistory',
            old_name='sync_instance_task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='syncinstancedetail',
            old_name='sync_instance_task_history',
            new_name='execution',
        ),
        migrations.RenameField(
            model_name='syncinstancedetail',
            old_name='sync_instance_task',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='syncinstancedetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Unsync'), (1, 'Synced'), (2, 'Synced'), (3, 'Released')], default=1, verbose_name='Status'),
        ),
        migrations.RenameModel(
            old_name='SyncInstanceTaskHistory',
            new_name='SyncInstanceTaskExecution',
        ),
        migrations.AlterField(
            model_name='syncinstancetaskexecution',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Failed'), (1, 'Succeed')], default=1, verbose_name='Status'),
        ),
    ]
