# Generated by Django 2.2.10 on 2020-03-11 07:10

import assets.models.utils
import common.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0014_auto_20200305_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeauthplanexecutionsubtask',
            options={'verbose_name': 'Change auth plan task'},
        ),
        migrations.AddField(
            model_name='changeauthplanexecutionsubtask',
            name='password',
            field=common.db.fields.EncryptCharField(blank=True, max_length=256, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='changeauthplanexecutionsubtask',
            name='private_key',
            field=common.db.fields.EncryptTextField(blank=True, max_length=4096, null=True, validators=[assets.models.utils.private_key_validator], verbose_name='SSH private key'),
        ),
        migrations.AddField(
            model_name='changeauthplanexecutionsubtask',
            name='public_key',
            field=common.db.fields.EncryptTextField(blank=True, max_length=4096, null=True, verbose_name='SSH public key'),
        ),
        migrations.AddField(
            model_name='changeauthplanexecutionsubtask',
            name='step',
            field=models.SmallIntegerField(choices=[(0, 'Ready'), (1, 'check_condition'), (2, 'Change auth'), (3, 'Verify auth'), (4, 'Save auth'), (10, 'Finished')], default=0, verbose_name='Step'),
        ),
        migrations.AlterField(
            model_name='changeauthplanexecution',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='xpack.ChangeAuthPlan', verbose_name='Change auth plan'),
        ),
        migrations.AlterField(
            model_name='changeauthplanexecutionsubtask',
            name='plan_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='xpack.ChangeAuthPlanExecution', verbose_name='Change auth plan execution'),
        ),
        migrations.RenameField(
            model_name='changeauthplanexecutionsubtask',
            old_name='plan_execution',
            new_name='execution',
        ),
        migrations.RenameModel(
            old_name='ChangeAuthPlanExecutionSubtask',
            new_name='ChangeAuthPlanTask',
        ),
    ]
