# Generated by Django 2.2.10 on 2020-07-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0018_syncinstancetask_covered_always'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncinstancetask',
            old_name='covered_always',
            new_name='is_always_update',
        ),
        migrations.AlterField(
            model_name='syncinstancetask',
            name='is_always_update',
            field=models.BooleanField(default=False, verbose_name='Always update'),
        ),
    ]
