# Generated by Django 2.2.10 on 2020-08-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0019_auto_20200707_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncinstancetask',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xpack.Account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='syncinstancetask',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.AdminUser', verbose_name='Admin user'),
        ),
        migrations.AlterField(
            model_name='syncinstancetask',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Node', verbose_name='Node'),
        ),
    ]
