# Generated by Django 2.2.13 on 2020-09-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0020_auto_20200819_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncinstancetask',
            name='hostname_strategy',
            field=models.CharField(blank=True, choices=[('instance_name', 'Instance name'), ('instance_name_partial_ip', 'Instance name and Partial IP')], default='instance_name_partial_ip', max_length=128, verbose_name='Hostname strategy'),
        ),
        migrations.AlterField(
            model_name='syncinstancedetail',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Unsync'), (1, 'New Sync'), (2, 'Synced'), (3, 'Released')], default=1, verbose_name='Status'),
        ),
    ]
