# Generated by Django 2.2.13 on 2020-09-21 03:01

import common.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0021_auto_20200907_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeauthplanexecution',
            name='plan_snapshot',
            field=common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Change auth plan snapshot'),
        ),
    ]
