# Generated by Django 3.1 on 2020-11-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0023_auto_20201105_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='attrs',
            field=models.JSONField(),
        ),
    ]
