# Generated by Django 3.1 on 2021-03-04 02:26
import time
import sys

from django.db import migrations

default_id = '00000000-0000-0000-0000-000000000002'


def migrate_xpack_default_org_id(apps, schema_editor):
    org_app_models = [
        ('xpack', [
            'Account', 'SyncInstanceDetail', 'SyncInstanceTask', 'SyncInstanceTaskExecution',
            'ChangeAuthPlan', 'ChangeAuthPlanExecution', 'ChangeAuthPlanTask',
            'GatherUserTask', 'GatherUserTaskExecution',
        ]),
    ]
    print("")
    for app, models_name in org_app_models:
        for model_name in models_name:
            t_start = time.time()
            print("Migrate model org id: {}".format(model_name), end='')
            sys.stdout.flush()

            model_cls = apps.get_model(app, model_name)
            model_cls.objects.filter(org_id='').update(org_id=default_id)
            interval = round((time.time() - t_start) * 1000, 2)
            print(" done, use {} ms".format(interval))


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0024_auto_20201119_1614'),
    ]

    operations = [
        migrations.RunPython(migrate_xpack_default_org_id)
    ]
