# Generated by Django 3.1 on 2021-02-25 07:21

import json
from django.db import migrations, models


def migrate_cloud_account_access_key_to_attrs(apps, schema_editor):
    cloud_account_model = apps.get_model("xpack", "Account")
    accounts = cloud_account_model.objects.all()
    for account in accounts:
        attrs = account.attrs
        if account.provider == 'azure':
            attrs.update({
                'client_id': account.access_key_id,
                'client_secret': account.access_key_secret
            })
        else:
            attrs.update({
                'access_key_id': account.access_key_id,
                'access_key_secret': account.access_key_secret
            })
        account.attrs = attrs

    cloud_account_model.objects.bulk_update(accounts, ['attrs'])


def migrate_cloud_execution_result_field(apps, schema_editor):
    execution_model = apps.get_model("xpack", "SyncInstanceTaskExecution")
    executions = execution_model.objects.all()
    for execution in executions:
        try:
            result = json.loads(execution.result)
        except Exception as e:
            result = {}
        execution.result_new = result

    execution_model.objects.bulk_update(executions, ['result_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0025_auto_20210304_1026'),
    ]

    operations = [
        migrations.RunPython(migrate_cloud_account_access_key_to_attrs),

        migrations.RemoveField(
            model_name='account',
            name='access_key_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='access_key_secret',
        ),
        migrations.RemoveField(
            model_name='syncinstancetask',
            name='instances',
        ),
        migrations.AddField(
            model_name='account',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='account',
            name='attrs',
            field=models.JSONField(default=dict, verbose_name='Attrs'),
        ),
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('aliyun', 'Alibaba Cloud'), ('aws_international', 'AWS (International)'), ('aws_china', 'AWS (China)'), ('azure', 'Azure (China)'), ('huaweicloud', 'Huawei Cloud'), ('qcloud', 'Tencent Cloud'), ('vmware', 'VMware')], default='aliyun', max_length=128, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='account',
            name='validity',
            field=models.BooleanField(default=False, max_length=2, verbose_name='Validity'),
        ),
        migrations.AlterField(
            model_name='syncinstancetask',
            name='regions',
            field=models.JSONField(default=list, verbose_name='Regions'),
        ),
        # migrate result field
        migrations.AddField(
            model_name='syncinstancetaskexecution',
            name='result_new',
            field=models.JSONField(default=dict, verbose_name='Result'),
        ),
        migrations.RunPython(migrate_cloud_execution_result_field),
        migrations.RemoveField(
            model_name='syncinstancetaskexecution',
            name='result',
        ),
        migrations.RenameField(
            model_name='syncinstancetaskexecution',
            old_name='result_new',
            new_name='result',
        ),
    ]
