# Generated by Django 3.1 on 2021-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0026_auto_20210304_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('aliyun', 'Alibaba Cloud'), ('aws_international', 'AWS (International)'), ('aws_china', 'AWS (China)'), ('azure', 'Azure (China)'), ('azure_international', 'Azure (International)'), ('huaweicloud', 'Huawei Cloud'), ('qcloud', 'Tencent Cloud'), ('vmware', 'VMware')], default='aliyun', max_length=128, verbose_name='Provider'),
        ),
    ]
