# Generated by Django 3.1 on 2021-04-08 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0027_auto_20210318_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('aliyun', 'Alibaba Cloud'), ('aws_international', 'AWS (International)'), ('aws_china', 'AWS (China)'), ('azure', 'Azure (China)'), ('azure_international', 'Azure (International)'), ('huaweicloud', 'Huawei Cloud'), ('qcloud', 'Tencent Cloud'), ('vmware', 'VMware'), ('nutanix', 'Nutanix')], default='aliyun', max_length=128, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='changeauthplan',
            name='username',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_@\\-\\.]*$', 'Special char not allowed')], verbose_name='Username'),
        ),
    ]
