# Generated by Django 3.1.6 on 2021-07-20 11:04

from django.db import migrations, models
import django.db.models.deletion
import xpack.plugins.cloud.models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0030_auto_20210713_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncinstancetask',
            name='ip_network_segment_group',
            field=models.JSONField(default=xpack.plugins.cloud.models.ip_network_segment_group_default, verbose_name='IP network segment group'),
        ),
        migrations.AddField(
            model_name='syncinstancetask',
            name='protocols',
            field=models.CharField(blank=True, default='ssh/22 rdp/3389', max_length=128, verbose_name='Protocols'),
        ),
    ]
