# Generated by Django 3.1.6 on 2021-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0031_auto_20210720_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeauthplanexecution',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual trigger'), ('timing', 'Timing trigger')], default='manual', max_length=128, verbose_name='Trigger mode'),
        ),
    ]
