# Generated by Django 3.1.6 on 2021-07-29 04:52

from django.db import migrations, models, transaction
import common.db.fields


def migrate_is_password_to_changeauthplanexecution(apps, schema_editor):
    change_auth_plan_execution_model = apps.get_model("xpack", "ChangeAuthPlanExecution")

    updates = list()
    with transaction.atomic():
        for instance in change_auth_plan_execution_model.objects.all():
            instance.plan_snapshot.update({'is_password': True})
            updates.append(instance)
        change_auth_plan_execution_model.objects.bulk_update(updates, ['plan_snapshot', ])


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0032_changeauthplanexecution_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeauthplan',
            name='is_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='changeauthplan',
            name='is_ssh_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changeauthplan',
            name='ssh_key_strategy',
            field=models.CharField(blank=True, choices=[('add', 'Append SSH KEY'), ('set', 'Empty and append SSH KEY'), ('set_jms', 'Empty current user and append SSH KEY')], max_length=128, null=True, verbose_name='SSH Key strategy'),
        ),
        migrations.AlterField(
            model_name='changeauthplan',
            name='password_rules',
            field=common.db.fields.JsonDictCharField(blank=True, max_length=2048, null=True, verbose_name='Password rules'),
        ),
        migrations.AlterField(
            model_name='changeauthplan',
            name='password_strategy',
            field=models.CharField(blank=True, choices=[('custom', 'Custom password'), ('random_one', 'All assets use the same random password'), ('random_all', 'All assets use different random password')], max_length=128, null=True, verbose_name='Password strategy'),
        ),
        migrations.RunPython(migrate_is_password_to_changeauthplanexecution),
    ]
