# Generated by Django 3.1.6 on 2021-08-10 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0033_auto_20210729_1252'),
        ('assets', '0076_delete_assetuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncinstancetask',
            old_name='admin_user',
            new_name='unix_admin_user',
        ),
        migrations.AlterField(
            model_name='syncinstancetask',
            name='unix_admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.systemuser', verbose_name='Unix admin user'),
        ),
        migrations.AddField(
            model_name='syncinstancetask',
            name='windows_admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windows_sync_instance_task', to='assets.systemuser', verbose_name='Windows admin user'),
        ),
        migrations.AlterField(
            model_name='syncinstancetask',
            name='unix_admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unix_sync_instance_task', to='assets.systemuser', verbose_name='Unix admin user'),
        ),
    ]
