# Generated by Django 3.1.12 on 2021-09-09 10:40

import common.db.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0076_delete_assetuser'),
        ('applications', '0011_auto_20210826_1759'),
        ('xpack', '0035_auto_20210827_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationChangeAuthPlan',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('is_periodic', models.BooleanField(default=False)),
                ('interval', models.IntegerField(blank=True, default=24, null=True, verbose_name='Cycle perform')),
                ('crontab', models.CharField(blank=True, max_length=128, null=True, verbose_name='Regularly perform')),
                ('password_strategy', models.CharField(blank=True, choices=[('custom', 'Custom password'), ('random_one', 'All assets use the same random password'), ('random_all', 'All assets use different random password')], max_length=128, null=True, verbose_name='Password strategy')),
                ('password_rules', common.db.fields.JsonDictCharField(blank=True, max_length=2048, null=True, verbose_name='Password rules')),
                ('password', common.db.fields.EncryptCharField(blank=True, max_length=256, null=True, verbose_name='Password')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=128, null=True, verbose_name='Created by')),
                ('category', models.CharField(choices=[('db', 'Database'), ('remote_app', 'Remote app'), ('cloud', 'Cloud')], max_length=16, verbose_name='Category')),
                ('type', models.CharField(choices=[('mysql', 'MySQL'), ('oracle', 'Oracle'), ('postgresql', 'PostgreSQL'), ('mariadb', 'MariaDB'), ('chrome', 'Chrome'), ('mysql_workbench', 'MySQL Workbench'), ('vmware_client', 'vSphere Client'), ('custom', 'Custom'), ('k8s', 'Kubernetes')], max_length=16, verbose_name='Type')),
                ('apps', models.ManyToManyField(related_name='change_auth_plans', to='applications.Application', verbose_name='Database')),
                ('system_users', models.ManyToManyField(related_name='change_app_auth_plans', to='assets.SystemUser', verbose_name='System user')),
            ],
            options={
                'verbose_name': 'Application change auth plan',
                'unique_together': {('org_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationChangeAuthPlanExecution',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Date start')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('plan_snapshot', common.db.fields.JsonDictTextField(blank=True, null=True, verbose_name='Change auth plan snapshot')),
                ('password', common.db.fields.EncryptCharField(blank=True, max_length=256, null=True, verbose_name='Password')),
                ('trigger', models.CharField(choices=[('manual', 'Manual trigger'), ('timing', 'Timing trigger')], default='manual', max_length=128, verbose_name='Trigger mode')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='xpack.applicationchangeauthplan', verbose_name='Application change auth plan')),
            ],
            options={
                'verbose_name': 'Application change auth plan execution',
            },
        ),
        migrations.CreateModel(
            name='ApplicationChangeAuthPlanTask',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('password', common.db.fields.EncryptCharField(blank=True, max_length=256, null=True, verbose_name='Password')),
                ('step', models.SmallIntegerField(choices=[(0, 'Ready'), (1, 'Preflight check'), (2, 'Change auth'), (3, 'Verify auth'), (4, 'Keep auth'), (10, 'Finished')], default=0, verbose_name='Step')),
                ('reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Reason')),
                ('is_success', models.BooleanField(default=False)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Date start')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('type', models.CharField(default='mysql', max_length=16, verbose_name='Type')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='App')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='xpack.applicationchangeauthplanexecution', verbose_name='Application change auth plan execution')),
                ('system_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.systemuser', verbose_name='System user')),
            ],
            options={
                'verbose_name': 'Application change auth plan task',
            },
        ),
    ]
