# Generated by Django 3.1.13 on 2021-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0036_applicationchangeauthplan_applicationchangeauthplanexecution_applicationchangeauthplantask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeauthplan',
            name='ssh_key_strategy',
            field=models.CharField(blank=True, choices=[('add', 'Append SSH KEY'), ('set', 'Empty and append SSH KEY'), ('set_jms', 'Replace (The key generated by JumpServer) ')], max_length=128, null=True, verbose_name='SSH Key strategy'),
        ),
    ]
