# Generated by Django 3.1.13 on 2022-02-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0040_auto_20220112_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeauthplan',
            options={'verbose_name': 'Asset change auth plan'},
        ),
        migrations.AlterModelOptions(
            name='changeauthplanexecution',
            options={'verbose_name': 'Asset change auth plan execution'},
        ),
        migrations.AlterModelOptions(
            name='changeauthplantask',
            options={'verbose_name': 'Asset change auth plan task'},
        ),
        migrations.AlterModelOptions(
            name='interface',
            options={'verbose_name': 'Interface setting'},
        ),
        migrations.AlterModelOptions(
            name='syncinstancedetail',
            options={'verbose_name': 'Sync instance detail'},
        ),
        migrations.AlterModelOptions(
            name='syncinstancetaskexecution',
            options={'verbose_name': 'Sync instance task execution'},
        ),
    ]
