# Generated by Django 3.1.14 on 2022-04-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0045_auto_20220329_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('aliyun', 'Alibaba Cloud'), ('aws_international', 'AWS (International)'), ('aws_china', 'AWS (China)'), ('azure', 'Azure (China)'), ('azure_international', 'Azure (International)'), ('huaweicloud', 'Huawei Cloud'), ('baiducloud', 'Baidu Cloud'), ('jdcloud', 'JD Cloud'), ('qcloud', 'Tencent Cloud'), ('vmware', 'VMware'), ('nutanix', 'Nutanix'), ('huaweicloud_private', 'Huawei Private Cloud'), ('qingcloud_private', 'Qingyun Private Cloud'), ('openstack', 'OpenStack'), ('gcp', 'Google Cloud Platform')], default='aliyun', max_length=128, verbose_name='Provider'),
        ),
    ]
