# Generated by Django 3.2.12 on 2022-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpack', '0047_auto_20220516_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='theme',
            field=models.CharField(default='classic_green', max_length=16, verbose_name='Theme'),
        ),
    ]
