# Generated by Django 3.1 on 2021-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_user_need_update_password'),
    ]

    operations = [
    ]
