# Generated by Django 3.1.6 on 2021-08-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210526_1100'),
    ]

    operations = [
    ]
