from . import aliyun
from . import qcloud
from . import aws_international
from . import aws_china
from . import huaweicloud
from . import azure
from . import vmware
from . import gcp
from . import baiducloud
from . import jdcloud
