- hosts: testhost
  vars:
    ansible_user: root
    ansible_ssh_password: Fit2Cloud20202
    user1: web
    user1password: Fit2Cloud@12344

  tasks:
    - name: Мониторинг паролей привилегированных пользователей
      ping:

    - name: Изменить пароль пользователя
      user:
        name: "{{ user1 }}"
        password: "{{ user1password|password_hash('sha512', 'K3mIlKK') }}"
        update_password: always

    - name: Убедитесь, что пароль был успешно изменен
      vars:
        - ansible_user: '{{ user1 }}'
          ansible_ssh_password: '{{ user1password }}'
      ping:

